graph TD
    A[User] --> B[React.js]
    B --> C[Node.js]
    B --> D[Express.js]
    C --> E[MongoDB]
    C --> F["TensorFlow.js"]
    C --> G[Jimp]
    D --> H[IPFS]
    H --> I[Pinata]
    I --> J["AWS S3"]
    C --> K[Ethers.js]
    K --> L["Polygon (MATIC)"]
    L --> M[OpenZeppelin]
    K --> N["Chainlink VRF"]
    O[Hardhat] --> M
    P[Postman] --> D
    Q[MythX] --> M
